require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CategoriesController, type: :controller do


  let(:valid_attributes) {
    {
      name: "Category Name"
    }
  }

  let(:invalid_attributes) {
    {
      name: ""
    }
  }

  let(:valid_session) { {} }
  let!(:category) { create :category }
  let(:user) { create :user }
  let(:admin) { create :admin }

  describe "GET #index" do
    it "assigns all categories as @categories" do
      get :index
      expect(assigns(:categories)).to eq([category]) 
    end
  end

  describe "GET #show" do
    it "assigns the requested category as @category" do
      get :show, params: {id: category.to_param}
      expect(assigns(:category)).to eq(category)
    end
  end

  describe "GET #new" do
    it "assigns a new category as @category" do
      allow(controller).to receive(:current_user).and_return(admin)
      get :new
      expect(assigns(:category)).to be_a_new(Category)
    end
  end

  describe "GET #edit" do
    it "assigns the requested category as @category" do
      allow(controller).to receive(:current_user).and_return(admin)
      get :edit, params: {id: category.to_param}
      expect(assigns(:category)).to eq(category)
    end
  end

  describe "POST #create" do
    before do
      allow(controller).to receive(:current_user).and_return(admin)
    end

    context "with valid params" do
      it "creates a new category" do
        expect {
          post :create, params: {category: valid_attributes}
        }.to change(Category, :count).by(1)
      end

      it "assigns a newly created category as @category" do
        post :create, params: {category: valid_attributes}
        expect(assigns(:category)).to be_a(Category)
        expect(assigns(:category)).to be_persisted
      end

      it "redirects to the created category" do
        post :create, params: {category: valid_attributes}
        expect(response).to redirect_to(Category.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved category as @category" do
        post :create, params: {category: invalid_attributes}
        expect(assigns(:category)).to be_a_new(Category)
      end

      it "re-renders the 'new' template" do
        post :create, params: {category: invalid_attributes}
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    before do
      allow(controller).to receive(:current_user).and_return(admin)
    end

    context "with valid params" do
      let(:new_attributes) {
        {
          name: "New Category Name",
        }
      }

      it "flashes the success message" do
        put :update, params: {id: category.to_param, category: new_attributes}
        expect(flash[:notice]).to eq("Category was successfully updated.")
      end

      it "updates the requested category" do
        put :update, params: {id: category.to_param, category: new_attributes}
        category.reload
        expect(category.name).to eq("New Category Name")
      end

      it "assigns the requested category as @category" do
        put :update, params: {id: category.to_param, category: valid_attributes}
        expect(assigns(:category)).to eq(category)
      end

      it "redirects to the category" do
        put :update, params: {id: category.to_param, category: valid_attributes}
        expect(response).to redirect_to(category)
      end
    end

    context "with invalid params" do
      it "assigns the category as @category" do
        category = create :category
        put :update, params: {id: category.to_param, category: invalid_attributes}
        expect(assigns(:category)).to eq(category)
      end

      it "re-renders the 'edit' template" do
        category = create :category
        put :update, params: {id: category.to_param, category: invalid_attributes}
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    before do
      allow(controller).to receive(:current_user).and_return(admin)
    end

    it "flashes the notice message" do
      delete :destroy, params: {id: category.to_param}
      expect(flash[:notice]).to eq("Category was successfully destroyed.")  
    end

    it "destroys the requested category" do
      expect {
        delete :destroy, params: {id: category.to_param}
      }.to change(Category, :count).by(-1)
    end

    it "redirects to the categories list" do
      delete :destroy, params: {id: category.to_param}
      expect(response).to redirect_to(categories_url)
    end
  end


end
